image: mcr.microsoft.com/playwright:v1.42.0-jammy

stages:
  - test

playwright_tests:
  stage: test

  script:
    - echo "ðŸ“¦ Setting up Node.js dependencies..."
    - npm ci
    
    - echo "ðŸš€ Running Playwright tests..."
    - npx playwright test

  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 30 days